apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tl-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tl-service
        tier: backend
        track: stable
    spec:
      containers:
      - name: card-service
        image: "achalise/tl-test:1.0"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_HOST
          value: mongo-tl-service
        - name: MONGO_PORT
          value: '27017'
---
apiVersion: v1
kind: Service
metadata:
  name: tl-service
spec:
  ports:
  - port: 8080
    targetPort: 6868
  selector:
    app: tl-service
    tier: backend
  type: NodePort

